### ISSUE TITLE
Add an option to use the system default font

### ISSUE THREAD

**Issue by mon-jai** [Mosc/Glider#94] opened 2023-10-23 18:13 UTC
It would be nice if we can change app font to Roboto instead.

**Comment by Mosc** [comment] 2023-10-23 18:24
Duplicate of #49. Unfortunately this is blocked by the Flutter framework.

**Closed by Mosc** 2023-10-23 18:24 UTC
Labels: duplicate, enhancement

**Comment by mon-jai** [comment] 2023-10-23 18:45
@Mosc How about adding Roboto as a font option?

It serves as Android's default font and looks closer to the iOS default font compared to Noto Sans.

**Comment by Mosc** [comment] 2023-10-23 18:51
That seems like a reasonable compromise. I will consider that.
