### ISSUE TITLE
Text rendering issues in comments 

### ISSUE THREAD

**Issue by Tintedfireglass** [Mosc/Glider#70] opened 2022-07-31 03:02 UTC
Video : 

https://media.discordapp.net/attachments/884641872008577064/1003134583153377340/VID-20220731-WA0000.mp4

The first comment doesn't render properly but when it is swiped left/right the text becomes normal

Another example : https://media.discordapp.net/attachments/884641872008577064/1003134444766511104/Screenshot_20220731-082727.png

looks like compression is causing it to look like it's not a problem. I'll try to find a way to upload full resolution footage.

Latest version
Android 12 Stock

**Comment by Tintedfireglass** [comment] 2022-07-31 03:03
It's clear in this image

https://media.discordapp.net/attachments/884641872008577064/1003135802097795132/Screenshot_20220731-083312-584.png

**Comment by Mosc** [comment] 2022-07-31 09:22
That is fascinating, haven't seen that before at all. At first I thought there might be something going on in the HTML rendering package used for comment text, but given that the username and time ago also render incorrectly that doesn't appear to be the case. Can you try to turn "use gestures" off on the settings page and see if that does anything?

**Comment by Tintedfireglass** [comment] 2022-07-31 10:19
> That is fascinating, haven't seen that before at all. At first I thought there might be something going on in the HTML rendering package used for comment text, but given that the username and time ago also render incorrectly that doesn't appear to be the case. Can you try to turn "use gestures" off on the settings page and see if that does anything?

No, even after it's turned off the bug doesn't go away

https://media.discordapp.net/attachments/884641872008577064/1003245209666207794/Screenshot_20220731-154808-839.png

**Comment by Tintedfireglass** [comment] 2022-07-31 10:20
Note that this bug has never occurred before the latest update.

**Comment by Tintedfireglass** [comment] 2022-07-31 16:58
> but given that the username and time ago also render incorrectly that doesn't appear to be the case.

they do render incorrectly, it just wasn't very noticeable 


https://media.discordapp.net/attachments/884641872008577064/1003345858114363453/Screenshot_20220731-2226552.png

**Comment by Mosc** [comment] 2022-07-31 18:29
Then my guess is that this is caused by a change in the Flutter framework. It appears to be triggered by text being rendered in a `Stack` widget which Glider uses to display the thread indicator.

**Comment by FarisZR** [comment] 2022-08-02 00:09
I have this issue too.
Its solved by closing and reopening the comment.

And it didn't exist before the latest update.

**Comment by Mosc** [comment] 2022-08-02 20:49
Would either of you be willing to test if this also occurs in the APK artifact produced in https://github.com/Mosc/Glider/actions/runs/2785088157? I've changed the Flutter version used by Glider to `stable` rather than `beta`, which I think might resolve the issue.

**Comment by Tintedfireglass** [comment] 2022-08-03 03:24
> Would either of you be willing to test if this also occurs in the APK artifact produced in https://github.com/Mosc/Glider/actions/runs/2785088157? I've changed the Flutter version used by Glider to `stable` rather than `beta`, which I think might resolve the issue.

Yes, I'm happy to test the APK. I don't think I am able to access it now though.

**Comment by azizLIGHT** [comment] 2022-08-03 04:38
> Would either of you be willing to test if this also occurs in the APK artifact produced in https://github.com/Mosc/Glider/actions/runs/2785088157? I've changed the Flutter version used by Glider to `stable` rather than `beta`, which I think might resolve the issue.

Is anyone able to use the APK artifact? I get a zip which doesn't seem to open, and if I rename it to .apk, it can't be parsed for installation

**Comment by Mosc** [comment] 2022-08-03 06:01
> > Would either of you be willing to test if this also occurs in the APK artifact produced in https://github.com/Mosc/Glider/actions/runs/2785088157? I've changed the Flutter version used by Glider to `stable` rather than `beta`, which I think might resolve the issue.
> 
> Yes, I'm happy to test the APK. I don't think I am able to access it now though.

Could it be because you were not logged in when you tried to access it?

> > Would either of you be willing to test if this also occurs in the APK artifact produced in https://github.com/Mosc/Glider/actions/runs/2785088157? I've changed the Flutter version used by Glider to `stable` rather than `beta`, which I think might resolve the issue.
> 
> Is anyone able to use the APK artifact? I get a zip which doesn't seem to open, and if I rename it to .apk, it can't be parsed for installation

Hmm, it should function as a normal ZIP which can be extracted. Here's a different link to the ZIP file, to see if that works better for you (GitHub doesn't allow directly uploading APK files): [app-release.apk.zip](https://github.com/Mosc/Glider/files/9248376/app-release.apk.zip).
 
You might need to uninstall the production version of Glider before Android will allow you to install this APK.

**Comment by Tintedfireglass** [comment] 2022-08-03 07:47
> Hmm, it should function as a normal ZIP which can be extracted. Here's a different link to the ZIP file, to see if that works better for you (GitHub doesn't allow directly uploading APK files): [app-release.apk.zip](https://github.com/Mosc/Glider/files/9248376/app-release.apk.zip).
>  
> You might need to uninstall the production version of Glider before Android will allow you to install this APK.


Yes, it has been fixed 
😀https://media.discordapp.net/attachments/884641872008577064/1004293950288449606/Screenshot_20220803-131526.png

**Comment by Mosc** [comment] 2022-08-03 10:51
Nice, that means 3244185d92e43c80611a087f779e8211a310f0b2 indeed fixed it. Will have to watch out for this when the current beta version moves into stable. I've kicked off a new release!

**Closed by Mosc** 2022-08-03 10:51 UTC
Labels: bug

**Comment by FarisZR** [comment] 2022-08-03 15:58
Yup that fixed it!
