### ISSUE TITLE
Bug: in-app gestures are incompatible with Android gesture navigation

### ISSUE THREAD

**Issue by ghost** [Mosc/Glider#55] opened 2022-04-02 15:09 UTC
For example, when you swipe from the right edge of the screen to the left, it triggers both in-app gesture and systemwide gesture. This could be solved by limiting in-app gestures to only the centre of the screen

**Comment by Mosc** [comment] 2022-04-05 19:36
Yes, this is a known issue. The "use gestures within the app" setting exists as a workaround for now. Closing because it's a duplicate of #32 and #36.

**Closed by Mosc** 2022-04-05 19:36 UTC
Labels: bug, duplicate
