### ISSUE TITLE
Glider 2.x doesn't have setting for dark theme on older Android without system setting

### ISSUE THREAD

**Issue by Porkepix** [Mosc/Glider#122] opened 2023-11-01 00:23 UTC
Older Android didn't have yet some system setting to set light or dark theme, and Glider 2.x only offer to reuse system setting for that, therefore it's not possible anymore on those devices to get a dark theme.

Issue seen on Android Oreo (8.0), stock ROM.

**Comment by Mosc** [comment] 2023-11-02 20:29
Duplicate of #115.

**Closed by Mosc** 2023-11-02 20:29 UTC
Labels: duplicate, enhancement
