### ISSUE TITLE
Scrolling should not go over the status bar

### ISSUE THREAD

**Issue by er4hn** [Mosc/Glider#10] opened 2021-04-14 03:54 UTC
Hello, first off, really enjoy the project. This has become my new hacker news reader app due to how it works well and has nice aesthetics. One issue I noticed is that when you scroll, the text at the top goes under the status bar. I've attached a picture showing what I mean at the very top:

![statusbar](https://user-images.githubusercontent.com/82489223/114652167-2be11500-9c9a-11eb-9be4-ace0b3bc6d5e.jpg)

For repo purposes this is on a Samsung Galaxy S8 running Android 9.

**Comment by Mosc** [comment] 2021-04-16 17:56
Text appearing behind a translucent status bar is exactly the intended behavior, actually, mostly because I think it usually looks nice. The thing that makes it awkward on Samsung devices appears to be that the Samsung status bar text and icons are translucent as well. Compare this to stock Android below, where the status bar text and icons are still readable within an acceptable level because they are opaque. I'm not sure about an appropriate solution yet.

![Screenshot_1618595460](https://user-images.githubusercontent.com/749107/115064507-47902980-9eed-11eb-95ea-dab3020faea0.png)

**Comment by er4hn** [comment] 2021-04-17 03:46
Ugh, someday I will get a pixel phone. Thanks for sharing that picture. If you like the look, hey, this is an opinionated client :)

**Comment by Mosc** [comment] 2021-08-19 21:25
The status bar and navigation bar have been darkened a bit for dark themes in a11ed6d57b3feddc55ef8f3063591c20c557e21f, which was released as part of v1.9.1.  Hopefully that improves the situation on your device somewhat. That's the most I'm willing to do at this point!

**Closed by Mosc** 2021-08-19 21:25 UTC
Labels: enhancement, wontfix
