### ISSUE TITLE
Feature Regression: The share button no longer saves title and link

### ISSUE THREAD

**Issue by erahn** [Mosc/Glider#100] opened 2023-10-25 05:52 UTC
The new version looks really pretty. Thanks for the work on it!

I do want to report a feature regression however: When trying to share to something that has a title / description field (in my case, I use trello to store things I want to look at later on my desktop) it no longer uses the API that fills in the HN title in the title and the HN URL in the description. Instead I can just choose to share Title, URL, or HN discussion URL. I would prefer to have the prior share method back as well.

Thanks!

**Comment by Mosc** [comment] 2023-10-25 19:17
An unintended regression indeed. Fixed in 2544628ae10068fb3b12a87294d23296bafdbe51, released as part of v2.1.0 that's rolling out now.

**Closed by Mosc** 2023-10-25 19:17 UTC
Labels: bug
